---

- hosts: all
  tasks:

  - name: Install python3-dnf
    become: true
    vars:
      ansible_python_interpreter: /usr/bin/python3
    ansible.builtin.dnf:
      name: python3-dnf
      state: present
    when: ansible_distribution == "CentOS"

  - name: update repo cache (CentOS)
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  roles:
    - base

- hosts: workstations
  roles:
    - workstations

- hosts: web_servers
  roles:
    - web_servers

- hosts: db_servers
  roles:
    - db_servers

- hosts: file_servers
  roles:
    - file_servers
